# Generated by Django 3.2.25 on 2024-10-17 22:43

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_content', '0002_added_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4BlockquoteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('quote_content_new', models.TextField(verbose_name='Quote')),
                ('quote_origin_new', models.TextField(blank=True, verbose_name='Cite')),
                ('quote_alignment_new', models.CharField(blank=True, choices=[('text-left', 'Left'), ('text-center', 'Center'), ('text-right', 'Right')], default='text-left', max_length=255, verbose_name='Alignment')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bootstrap4_content.bootstrap4blockquote')),
            ],
            options={
                'verbose_name': 'bootstrap4 blockquote Translation',
                'db_table': 'bootstrap4_content_bootstrap4blockquote_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
