# Generated by Django 3.2.25 on 2024-10-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_content', '0003_bootstrap4blockquotetranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap4blockquotetranslation',
            old_name='quote_alignment_new',
            new_name='quote_alignment',
        ),
        migrations.RenameField(
            model_name='bootstrap4blockquotetranslation',
            old_name='quote_content_new',
            new_name='quote_content',
        ),
        migrations.RenameField(
            model_name='bootstrap4blockquotetranslation',
            old_name='quote_origin_new',
            new_name='quote_origin',
        ),
        migrations.RemoveField(
            model_name='bootstrap4blockquote',
            name='quote_alignment',
        ),
        migrations.RemoveField(
            model_name='bootstrap4blockquote',
            name='quote_content',
        ),
        migrations.RemoveField(
            model_name='bootstrap4blockquote',
            name='quote_origin',
        ),
    ]
